[build]
  command = "npm run build"
   publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build"
  publish = ".next"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
