"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import HeaderBoxx from "./components/HeaderBoxx";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

interface Metadata {
  title: string;
  description: string;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://embed.tawk.to/66c60522ea492f34bc0898d4/1i5qo83rm";
    script.async = true;
    script.charset = "UTF-8";
    script.setAttribute("crossorigin", "*");
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBoxx />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
